### ISSUE TITLE
Add parameter: POT and square

### ISSUE THREAD

**Issue by FunkMonkey** [twolfson/spritesmith#29]
In some situations you need power-of-two textures. It would be nice, if that could be added as an option, so that the resulting texture will have power-of-two width and height (thus probably wasting space).

While we are at it, the `square` parameter would force width and height to be the same POT value.

Thanks!

**Comment by email2markt** [comment]
Sorry to drag up an old thread, but would a "power of two packer" algo be another approach?  It would lay things out in a way that is sympathetic/suitable to systems that offer mipmapping etc. and would always return width and heights that are a power of 2.

**Comment by twolfson** [comment]
On a more recent issue, @marekventur noted that there was no performance benefits to power of 2 images. Maybe check out this thread?

https://github.com/twolfson/gmsmith/pull/14#issuecomment-225533738

Also, @marekventur seems to author another packing system which might better suit your needs:

https://github.com/gamevy/pixi-packer

**Comment by email2markt** [comment]
So power of 2 sprites help with mipmapping, so that spritesheets of varying sizes can be created on the fly for use with WebGL.

Thanks for the pixi-packer link, unfortunately like so many of the solutions out there it has external dependencies.  What I like about spritesmith (combined with pixelsmith) is that it all works on all platforms and all dependencies can be installed through npm

I had hoped to tweak spritesmith to work in my circumstance without changing the core spritesmith js itself but I can't find a way right now.

**Comment by twolfson** [comment]
Ah, I see. I'm still quite firm on this not needing to be in `spritesmith's` core. However, it should be possible to get POT padding relatively easily. Here are some proposals:

- Write a `gulp`/`grunt` plugin which take an image and uses `pixelsmith` to place image on a padded POT canvas
- Write a custom packer (what you alluded to earlier) that does normal placement but adjusts custom height/width for entire canvas to have POT padding
    - `pixelsmith` should respect those dimensions
        - https://github.com/twolfson/pixelsmith/blob/2.1.1/lib/canvas.js#L10-L14
    - We might need to add support for custom algorithms that go around `layout` entirely so custom widths/heights can be used (or maybe add options for `layout` to override width/height)
    - I would prefer to avoid this method as it's not in the main use case of `spritesmith` =/
