### ISSUE TITLE
Spritesmith: x and y position generated is wrong when using varying sizes of images.

### ISSUE THREAD

**Issue by einsteinreloaded** [twolfson/spritesmith#79]
The x and y generated is incorrect when different sized images are used for sprite generation in spritesmith npm.

**Comment by twolfson** [comment]
Can you provide an example case where this is failing?

**Comment by einsteinreloaded** [comment]
I am trying with 120*40 px, 24*24px , 40*40px size of images. and generating the css 
`let spriteTemplateFunction = function (data,iconSlugs,spritePath) {
	var shared = ".brand-icon-retina { background-image: url('I'); }".replace(
		"I",
		spritePath
	);
	var perSprite = Object.keys(data.coordinates)
		.map(function (key,index) {
			let sprite = data.coordinates[key];
			return ".brand-icon-retina_N { width: Wpx; height: Hpx; background-position: Xpx Ypx; }"
				.replace("N", iconSlugs[index])
				.replace("W", sprite.width)
				.replace("H", sprite.height)
				.replace("X", sprite.x)
				.replace("Y", sprite.y);
		})
		.join("\n");

	return shared + "\n" + perSprite;
};
`
I am using this function to generate sprite css from the output of spritesmith

**Comment by twolfson** [comment]
CSS sprites require using a negative `background-position` for what seems an obvious positive position. This is due to implementation. If you update to the following then it should work:

```js
.replace("X", -sprite.x)
.replace("Y", -sprite.y);
```

Reference in the `grunt-spritesmith` and `gulp.spritesmith` libraries:

- https://github.com/twolfson/spritesheet-templates/blob/10.2.4/test/expected_files/scss.scss#L24-L27
- https://github.com/twolfson/spritesheet-templates/blob/10.2.4/test/expected_files/scss.scss#L86
